### ISSUE TITLE
Antiyoy on Linux

### ISSUE THREAD

**Issue by Gabirel** [yiotro/Antiyoy#12]
I love your game and I've already addicted to it.

Have you ever considered moving this lovely game onto Linux?

It would be pretty interesting thing if it could run on Linux

**Comment by yiotro** [comment]
Hi.

Check this out, I think it should run on linux:
https://drive.google.com/open?id=0BxeMGUGJe7XWQm9ZVGNhTDZhV2c

**Comment by Gabirel** [comment]
:sunglasses: OH MY GOD. That's awesome. It runs on Linux very well.

thanks.
