### ISSUE TITLE
Online multiplayer functionnality ?

### ISSUE THREAD

**Issue by ghost** [yiotro/Antiyoy#13]
Hi !
I like very much your game, and I've thinked about a new functionnality: playing online !

I know i'ts a very hard and long work but this can makes your game better, I've already created Android applications and tryed to create games. I would have forked your project, but i suppose you have built it using LibGdx, which i don't know really how it works.

**Comment by yiotro** [comment]
Hi.

Yeah, online would be nice but at this point I don't think that I can support that.

**Comment by poida** [comment]
@yiotro what about integrating with something like [Google Play Game Services](https://developers.google.com/games/services/)?

**Comment by yiotro** [comment]
Same answer. I don't know how to do online multiplayer in any form. I have no experience with it.

**Comment by dpoetzsch** [comment]
I love this game and I'm keen to give it a go. I looked into google play game services and I think it should be possible to implement it, even with AIs, using this technique https://stackoverflow.com/a/40333790/3594403.

For now, is there already anything I can use for a start?

**Comment by yiotro** [comment]
Little update to my previous comment: I've saw how client sends and receives info from server in libgdx, but that's all. 

About your last question: I don't know how those services work and what do they need. Also, source code that handles game mechanics requires huge refactoring if you want to add network feature.
