### ISSUE TITLE
Towers should be upgradable

### ISSUE THREAD

**Issue by gespinha** [yiotro/Antiyoy#23]
Hey! Just finished the whole campaign on Android and just wanted to give a quick feedback. This game is already amazing!

On complicated skirmishes, where the map is large and you're battling several kingdoms at once, not being able to upgrade tower is a true bottleneck for planning your defences ahead. Having a way to upgrade them (but not downgrade). In order not to break the balance of the game, allowing upgrades on towers only would do the trick.

What do you think?

Side note: the prototype-like design and map skins could look a little more polished. Improving this could drastically boost engagement on the Google Play Store.

**Comment by yiotro** [comment]
Hi.

Hmm, you should be able to place strong towers just on top of usual ones.

**Comment by subchannel13** [comment]
@gespinha As dev said you can upgrade towers, at least 15 credit one (2 strength) to 35 credit one (3 strength) BUT it costs full 35 credits, no discount.
