### ISSUE TITLE
New "Fog mode" request

### ISSUE THREAD

**Issue by gespinha** [yiotro/Antiyoy#24]
Hey!

Just a quick idea. Adding a "Fog Mode", would make the game a little more interesting.

This could work by displaying a silhouette of the map area but with no colors and the user would be able to see as far as X amount of cells from his border. This view range would depend on the presence of towers.

Do you think this makes sense?

Thanks!

**Comment by McAroni** [comment]
I like this idea! This could add some nice difficulty to the game

**Comment by yiotro** [comment]
Yeah, this idea is nice. I'll think about adding it to the game as optional feature :)
