### ISSUE TITLE
[Question] What's that?

### ISSUE THREAD

**Issue by airon90** [yiotro/Antiyoy#29]
When you press on a build some "shields" appear but in the Help there is nothing about it. Can somebody explain, please?

**Comment by Arkanosis** [comment]
Shields indicate where the enemy can't move without having an unit strong enough to destruct the building. Eg. a peon can't move next to a town center, a light soldier can't move next to a light tower…

**Comment by yiotro** [comment]
Yeah, exactly that. It's just a visual indicator, nothing more.

**Comment by airon90** [comment]
Thank you for your answer!
