### ISSUE TITLE
Watch saved replay

### ISSUE THREAD

**Issue by yoavst** [yiotro/Antiyoy#44]
How do you watch the saved "video" replays?

**Comment by Arkanosis** [comment]
Hi!

Main screen → Gear → More → Replays.

Have fun! :-)

**Comment by yoavst** [comment]
Thanks! 
Maybe it should be in a more visible menu?

**Comment by Arkanosis** [comment]
> Maybe it should be in a more visible menu?

I agree, I'd expect it in the main menu (next to “load game”).

**Comment by yiotro** [comment]
Yeah, I agree, it's not the best place for replays button.
I plan to put it in 'load' menu in next update. Probably at top right corner.
