### ISSUE TITLE
NullPointerException on game ending

### ISSUE THREAD

**Issue by yoavst** [yiotro/Antiyoy#47]
Finished level 91, wanted to save the reply because I was proud of the win, unfortunately, a null pointer! so sad.

Device is Essential phone PH1, on Android 8.1.
![image](https://user-images.githubusercontent.com/3912269/39071858-4132f210-44f1-11e8-9b65-de114ebcb81f.png)

**Comment by yiotro** [comment]
Yeah, that's my fault, sorry :( 

I hope you have it autosaved so you won't need to beat that level again.

Please update to latest version, this problem should be fixed there.
