### ISSUE TITLE
Play Store Support for Samsung Galaxy Note 10.1 (2014)

### ISSUE THREAD

**Issue by arendtio** [yiotro/Antiyoy#49]
I have a `Samsung Galaxy Note 10.1 (2014)` Tablet and when I search for 'antiyoy' in the Google Play Store I can't find the game. So I took the apk from my Samsung Galaxy S3 and it just worked and I wondered why the game is not available for the tablet? After all, playing the game with the tablet is more fun and the battery lasts longer too (Antiyoy is incredibly battery hungry) ;-)

Some more information about the tablet:
Model: SM-P605
Android Version: 5.1.1

**Comment by yiotro** [comment]
Ok, I've made it available for your tablet. But I may reverse this if people will report about crashes on it.

**Comment by arendtio** [comment]
Thanks, now I can find and install it :+1:
