### ISSUE TITLE
Feature request: show all tower shields instead of just one

### ISSUE THREAD

**Issue by MichaelS11** [yiotro/Antiyoy#50]
Great game! :)

When clicking on a tower, would it be possible to show all the tower shields for that territory, instead of just the one? This would make it easier to see what area is covered and where best to place a new tower.

**Comment by yiotro** [comment]
Hmm, that's interesting idea.
There is only one problem: on large territories there may be too much shields at one time which can cause fps drop. But it can be easily fixed by applying distance limit for those shields (not show all, but only nearby ones).
I'll think about it.

**Comment by MichaelS11** [comment]
Sounds great, having a limit to the number of shields shown would be smart.

**Comment by OvermindDL1** [comment]
Or just draw all the shields in a single batched and cached draw call, shouldn't have much cost then.

**Comment by MichaelS11** [comment]
Looks like this was implemented, thank you very much! :)

What do you think about having different shield colors depending on power level / protection level?

**Comment by yiotro** [comment]
Nice to see that update was processed to GP so fast. I actually thought that it takes longer. About your idea:
1. It will be quite unobvious for players and require to add explanations.
2. To be sure that it can be rendered without switching texture I will have to make it slightly more complicated, which is always not a good thing.

**Comment by MichaelS11** [comment]
If the colors matched or where similar to the tower colors then it would be pretty straight forward.
