### ISSUE TITLE
User map K. War has no AI

### ISSUE THREAD

**Issue by MichaelS11** [yiotro/Antiyoy#56]
When I played the user map K. War there was no AI enabled. Was able to play both sides. Is this expected?

**Comment by yiotro** [comment]
It was intended, but I think that would be better to change it to just usual single player.

**Comment by MichaelS11** [comment]
I think changing that map to single player with AI would be good too :)

**Comment by MichaelS11** [comment]
Looks to be fixed, thanks! :)
