### ISSUE TITLE
Barons can unbalance or stall the game

### ISSUE THREAD

**Issue by ThrawnCA** [yiotro/Antiyoy#6]
Although Barons are expensive to support, they are immune to direct assault. If a baron can command a choke point with enough territory behind to support him, then it is impossible for anyone to attack him, no matter how large and rich they are.

Against the AI, this recently allowed me to defeat a much larger opponent head-on, simply by building up a huge number of farms until I could build multiple barons and start pushing back. It doesn't matter how expensive farms get, when you can take as long as you want because there's no possibility of retaliation. This seems unbalanced; the computer had more resources than I did, but no advantage over me.

Against a human opponent, it would likely result in stalemate, with barons blocking each other.

I realise that this is somewhat inherent in the original rules of Slay; however, the introduction of farms makes it much more potent, since barons can be supported by a much smaller space, and can build up their income while stalling.

**Comment by ThrawnCA** [comment]
I'm not sure, offhand, what's the best way to counteract this. Perhaps units should keep scaling (and tripling their maintenance cost each time)? That probably would have worked in this case; I expect that the computer could have built a super-baron before I was ready to push back.

**Comment by yiotro** [comment]
Well, I think that the best to deal with this is to introduce some kind of ranged attack unit. Maybe something that can only attack knights and barons, idk. 
I know about this problem and I will try to fix that, but can't say when I will be able to do that.

**Comment by ThrawnCA** [comment]
Hmm. Yes, the possibility of an attack that works only against barons did occur to me (no need for anything special against knights; barons can take care of them). A bit like the Spy in Stratego. However, it seemed like it would be a bigger change, both conceptually and in code. Whereas providing a fifth soldier type would be a very logical extension of the rules, rarely needed but operating the same way as every other unit. Especially when you've similarly provided an upgrade for towers.

In theory, it would be possible to have a similar stalemate with level 5 troops. However, it seems very unlikely that two powers would obtain them at exactly the same time, and even more unlikely that anyone could field enough of them to support a serious offensive. They would just be tiebreakers.

**Comment by yiotro** [comment]
Well, I meant that new unit will be able to kill baron (and knight maybe, idk), but will be very vulnerable to other units. So it will be very weak unit that just resolves stalemate situations.

**Comment by ThrawnCA** [comment]
Yes, that's just like the Spy in Stratego. But I don't think it's the best solution here. It would bring too many changes - especially if you give it range. Would that mean that it could jump past other defences? Or natural obstacles? If it can attack knights, then can it attack towers? It presumably can't attack peasants, but can peasants attack it? How much should it cost?

Whereas just adding a fifth (or even sixth) soldier level would be simple. The rules would work exactly like the existing soldiers.

**Comment by ThrawnCA** [comment]
This is obsolete as barons can now kill each other.
