### ISSUE TITLE
Feature request: Show shields when building tower

### ISSUE THREAD

**Issue by MichaelS11** [yiotro/Antiyoy#69]
Greetings,

Was wondering if the shields could be shown when a tower has been selected to be built? This way it is easier to decide where to place the tower.

Thank you,

Michael

**Comment by yiotro** [comment]
Hi.

Player chooses tower location by single tap. Before that it's impossible to predict where he will place it. After that there is no point. 

When exactly those shields should be displayed? And how to know where to show them?

**Comment by MichaelS11** [comment]
Was requesting the same shield display that happens when one clicks on a tower or town.

**Comment by yiotro** [comment]
Please describe how exactly it should work in your opinion. 

So player chooses to build tower. And game shows shields around what hex?

**Comment by MichaelS11** [comment]
It would shows the shields around any hex that has a tower already place. This is so I can figure out where to place the new tower that is not already defended by a tower.

**Comment by yiotro** [comment]
Ok, I understood. Well, I'll think about it, but I don't really think that it's needed. I recommend you to switch skin to 'grid', it will help to see which hex are where. Towers always defend nearby hexes, so it should be easy to detect that.

**Comment by MichaelS11** [comment]
I am on hex skin. Up to you of course. I understand that towers always defend nearby hexes. When trying to place a tower between/near two or three other towers, it would make it easier to see what is being defended and therefore quicker to place a new tower.

Thanks for a great game! :)

**Comment by yiotro** [comment]
You're welcome :)

**Comment by maphew** [comment]
So another way to word this idea is: "highlight all existing defended hexes when [build tower] is selected".

And/or highlight undefended areas, similar to the way possible build locations are currently shown when building a house.

**Comment by MichaelS11** [comment]
Yes, that is a good way to put it :)

**Comment by MichaelS11** [comment]
This would still be really helpful to me and I think others, any chance for getting it added?

**Comment by yiotro** [comment]
No, as I've said, I think that it's not needed. It's already quite easy to see which areas are defended. These shields would just create visual clutter that will make it harder to understand what is going on on screen.

**Comment by MichaelS11** [comment]
Ok, thank you
