### ISSUE TITLE
Hunter Vs Gatherer user map un-playable after restart

### ISSUE THREAD

**Issue by MichaelS11** [yiotro/Antiyoy#70]
Greetings,

In my settings I have it selected to default to green player. When playing the Hunter Vs Gatherer user map the first time from the main menu it seems to be working fine. I am playing the red player, which I assume is correct. On restart of that map, it shows the green players jumping but I can not click on them to move them. I can click on the red player land and create a new guy. I can not move the guys that are already there. Not sure if it is a issue with this map only or something that could happen with other maps. I am playing on a Android phone.

**Comment by yiotro** [comment]
Hi.

> In my settings I have it selected to default to green player

Hmm, are you talking about campaign options or skirmish options? 

Either way, those options don't apply to user levels. In user levels your color is always defined by map author.

> When playing the Hunter Vs Gatherer user map the first time from the main menu it seems to be working fine. I am playing the red player, which I assume is correct. On restart of that map, it shows the green players jumping but I can not click on them to move them

Yeah, you're right. I've checked it out and something really crazy is going on :D

Thanks for reporting about this problem, I'll fix it in next update.

**Comment by MichaelS11** [comment]
Fixed
