### ISSUE TITLE
Diplomacy Letter Empty

### ISSUE THREAD

**Issue by MichaelS11** [yiotro/Antiyoy#75]
Was playing user map Rise of civilizations and clearing the Letter every turn for a few turns. Then the Letters nofication icon was showing up but there was no Letters, just empty / blank white area on the screen. Saving that game and then loading it back up did not fix the issue. Had save the game, exit out complety, open app back up, then load saved game back up and Letters came back.

**Comment by yiotro** [comment]
Thanks for bug report.
Is there a 100% way to reproduce this problem?

**Comment by MichaelS11** [comment]
Not that I found.

Also sometimes the Letter would be there but no text. Would just see the color with no text. Would still be able to click on it.

Noticed that the colors in Diplomacy does not usually match the players' color, is that expected?

**Comment by yiotro** [comment]
One more question: are you sure that you're playing on latest version of
the game?

вс, 20 окт. 2019 г. в 19:06, MichaelS11 <notifications@github.com>:

**Comment by MichaelS11** [comment]
Version 1.25g

**Comment by yiotro** [comment]
Ok, thanks.
It's not the latest version, but I think that latest version also has
similar problem.
Currently I don't know what is causing it and how to reproduce it, so I
can't promise that I'll fix it.

вс, 20 окт. 2019 г. в 21:02, MichaelS11 <notifications@github.com>:

**Comment by MichaelS11** [comment]
Thanks for looking into it :)

**Comment by yiotro** [comment]
You're welcome.

ср, 20 нояб. 2019 г. в 08:13, MichaelS11 <notifications@github.com>:
