### ISSUE TITLE
Antiyoy map submission

### ISSUE THREAD

**Issue by MichaelS11** [yiotro/Antiyoy#82]
Here is a large map submission, hopefuly fun for people.

`antiyoy_level_code#level_size:9#general:4 1 11#map_name:Slot 2#editor_info:1 false true #land:24 16 7 0,21 16 7 0,28 12 7 0,27 12 7 0,24 15 7 0,28 13 7 0,23 15 7 0,25 14 7 0,47 30 7 0,15 18 7 0,15 19 7 0,16 17 7 0,16 18 7 0,16 19 7 0,16 20 7 2,17 15 7 0,17 16 7 0,17 17 7 0,17 19 7 0,17 20 10 0,17 21 10 3,17 26 7 0,17 27 7 2,17 29 5 0,17 37 4 3,18 14 7 0,18 15 7 1,18 16 7 0,18 17 7 0,18 18 7 0,18 19 10 0,18 25 7 0,18 26 7 0,18 29 5 0,18 36 4 0,19 11 3 0,19 12 7 0,19 13 7 0,19 14 7 0,19 15 7 0,19 16 7 0,19 24 7 0,19 25 7 0,19 26 7 0,19 29 5 3,19 30 7 0,19 31 7 0,19 32 7 0,19 36 7 0,20 9 7 2,20 10 3 0,20 11 3 0,20 12 7 0,20 13 7 2,20 14 7 0,20 15 7 0,20 16 7 0,20 24 7 0,20 25 7 2,20 26 7 0,20 27 7 0,20 28 7 0,20 31 7 0,20 34 7 0,20 35 7 0,20 37 2 3,21 8 7 0,21 9 3 3,21 10 3 0,21 11 7 0,21 13 7 0,21 14 7 0,21 15 7 0,21 21 9 0,21 22 9 0,21 23 9 3,21 24 7 0,21 27 7 0,21 28 7 0,21 29 7 0,21 30 7 0,21 31 7 0,21 32 7 0,21 33 7 2,21 34 7 2,21 36 7 0,21 37 2 2,22 7 7 0,22 8 7 0,22 9 7 0,22 10 7 0,22 11 7 2,22 12 7 0,22 13 7 0,22 14 7 0,22 15 7 0,22 16 7 0,22 17 7 0,22 22 7 0,22 24 7 0,22 25 7 0,22 26 7 0,22 27 7 0,22 28 7 0,22 29 7 0,22 30 7 0,22 31 7 0,22 32 7 0,22 33 7 0,22 34 7 0,22 35 7 0,22 37 2 0,23 7 7 0,23 8 7 1,23 9 7 0,23 10 7 0,23 11 7 0,23 12 7 0,23 13 7 2,23 14 7 0,23 16 7 0,23 17 7 0,23 23 7 0,23 24 7 0,23 25 7 0,23 26 7 0,23 27 7 0,23 28 7 1,23 29 7 0,23 30 7 0,23 31 7 0,23 32 7 0,23 33 7 0,23 35 7 0,24 5 7 0,24 6 7 0,24 7 7 0,24 8 7 0,24 9 7 0,24 10 7 0,24 11 7 0,24 14 7 0,24 21 7 0,24 22 7 0,24 23 7 1,24 24 7 0,24 25 7 1,24 26 7 0,24 27 7 2,24 28 7 0,24 29 7 0,24 30 7 0,24 32 7 0,24 33 7 2,25 5 7 0,25 6 7 0,25 7 7 0,25 8 7 0,25 9 3 3,25 10 3 0,25 13 7 0,25 15 7 0,25 16 7 2,25 19 7 0,25 20 7 0,25 21 7 0,25 22 7 1,25 23 7 0,25 24 7 0,25 25 7 0,25 26 7 0,25 30 7 0,25 32 7 0,25 33 7 0,26 6 7 2,26 8 3 0,26 9 3 0,26 10 7 0,26 12 7 0,26 13 7 0,26 14 7 0,26 19 7 0,26 20 7 0,26 21 7 0,26 22 7 0,26 23 7 0,26 24 7 0,26 26 7 0,26 28 10 0,26 29 10 3,26 30 7 2,26 31 7 0,26 32 7 0,27 3 7 0,27 4 7 0,27 5 7 0,27 7 7 0,27 8 3 0,27 9 7 0,27 13 7 0,27 14 7 0,27 18 7 2,27 19 7 0,27 20 7 0,27 21 7 0,27 22 7 0,27 23 7 2,27 24 7 0,27 25 7 0,27 26 10 0,27 27 10 0,27 28 10 0,27 29 7 0,27 30 7 2,27 32 7 0,28 2 7 0,28 5 7 0,28 14 7 0,28 15 4 0,28 16 4 0,28 17 4 3,28 18 7 0,28 20 7 0,28 21 7 0,28 22 7 0,28 25 7 0,28 26 7 0,28 28 7 0,28 29 7 0,28 30 7 0,28 31 7 0,28 32 7 2,29 12 7 0,29 13 7 0,29 14 4 0,29 15 4 0,29 17 7 0,29 18 8 0,29 19 8 3,29 20 7 0,29 21 7 0,29 22 7 0,29 24 7 0,29 25 7 0,29 26 7 0,29 27 7 0,29 28 7 0,29 29 7 0,29 31 7 0,29 32 7 0,30 11 7 2,30 12 7 0,30 13 7 0,30 14 7 0,30 15 7 0,30 16 7 0,30 17 8 0,30 18 8 0,30 19 7 0,30 20 7 0,30 21 7 0,30 22 7 0,30 23 7 0,30 24 7 0,30 25 7 0,30 26 7 0,30 27 7 0,30 28 7 0,30 29 7 0,30 30 7 0,30 31 6 0,31 11 6 3,31 12 7 0,31 13 7 0,31 14 7 0,31 15 7 1,31 16 7 0,31 17 8 0,31 18 7 1,31 19 7 0,31 20 7 0,31 21 7 0,31 22 7 0,31 23 7 0,31 24 7 0,31 25 7 0,31 26 7 0,31 27 7 0,31 28 7 0,31 31 6 3,32 11 6 0,32 12 6 2,32 13 7 0,32 14 7 0,32 15 7 0,32 16 7 0,32 17 7 0,32 18 7 0,32 19 7 0,32 20 7 1,32 21 7 1,32 22 7 0,32 23 7 0,32 24 7 0,32 25 7 0,32 26 7 0,32 27 7 0,32 28 7 0,33 11 6 0,33 13 7 0,33 14 7 0,33 15 7 0,33 16 7 0,33 17 7 0,33 18 7 0,33 19 7 0,33 20 7 1,33 21 7 1,33 22 7 0,33 23 7 0,33 24 7 2,33 26 7 0,33 28 7 0,33 29 7 0,34 12 7 0,34 13 7 0,34 14 7 0,34 15 7 0,34 16 7 1,34 17 7 0,34 18 7 0,34 19 7 0,34 20 7 0,34 21 7 0,34 22 7 0,34 23 7 0,34 25 7 0,34 26 7 0,34 27 7 0,34 29 0 0,35 12 7 0,35 13 7 0,35 14 7 0,35 15 7 0,35 16 7 0,35 17 7 0,35 18 7 0,35 19 7 0,35 20 7 0,35 21 7 0,35 22 7 0,35 23 7 0,35 24 7 0,35 25 7 0,35 26 7 0,35 28 0 3,35 29 0 2,36 10 2 0,36 11 2 3,36 12 2 1,36 13 7 0,36 14 7 0,36 15 7 0,36 16 7 0,36 17 7 0,36 18 7 0,36 19 7 0,36 20 7 0,36 21 7 0,36 22 7 0,36 23 7 0,36 24 7 0,37 11 2 0,37 12 7 0,37 13 7 0,37 14 7 0,37 15 7 1,37 16 7 0,37 17 4 3,37 18 4 0,37 19 7 0,37 20 7 0,37 21 7 0,37 22 7 0,37 23 7 0,38 10 7 0,38 11 7 1,38 12 7 0,38 13 7 0,38 14 7 0,38 15 7 0,38 16 4 0,38 17 4 0,38 18 7 0,38 19 7 0,38 20 7 0,38 21 7 1,38 22 7 0,38 23 7 0,38 25 7 0,39 9 7 0,39 10 7 0,39 11 7 0,39 12 7 0,39 13 7 0,39 14 7 0,39 15 7 1,39 16 4 0,39 17 7 0,39 18 7 0,39 19 7 0,39 20 7 0,39 21 7 0,39 22 7 0,39 23 7 0,39 24 7 0,39 25 7 0,40 7 7 0,40 8 7 0,40 9 7 0,40 10 7 0,40 11 7 0,40 12 7 0,40 13 7 1,40 14 7 0,40 15 7 0,40 16 7 0,40 17 7 1,40 18 7 0,40 19 7 0,40 20 7 0,40 21 7 0,40 22 7 1,40 23 7 0,40 24 7 0,40 25 7 0,40 26 7 0,41 5 1 3,41 6 1 0,41 8 7 0,41 9 7 0,41 10 7 0,41 11 7 0,41 12 7 0,41 13 7 0,41 14 7 0,41 15 7 0,41 16 7 1,41 17 7 0,41 18 7 0,41 19 7 0,41 20 7 0,41 21 7 1,41 22 7 0,41 24 7 0,41 25 5 3,41 26 5 0,42 7 7 0,42 8 7 0,42 9 7 0,42 10 7 0,42 11 7 0,42 12 7 0,42 13 7 0,42 14 7 0,42 15 7 0,42 16 7 0,42 17 7 0,42 18 7 0,42 19 7 0,42 20 7 0,42 21 7 0,42 22 7 0,42 23 7 0,42 24 7 2,42 25 5 0,43 5 2 0,43 6 2 3,43 8 7 0,43 9 7 0,43 11 10 2,43 12 7 0,43 14 7 0,43 16 7 0,43 17 7 0,43 18 7 0,43 19 7 0,43 20 7 0,43 21 7 0,43 25 5 0,43 28 4 3,44 7 7 0,44 8 7 0,44 9 7 0,44 10 10 0,44 11 10 0,44 12 7 0,44 13 7 0,44 14 7 0,44 15 7 0,44 16 7 0,44 17 7 0,44 18 7 0,44 19 7 0,44 20 7 0,44 27 4 2,45 10 10 3,45 11 10 0,45 12 7 0,45 13 7 0,45 14 7 2,45 15 7 0,45 16 7 0,45 18 7 2,45 19 7 0,45 20 7 0,45 22 9 3,45 25 7 0,45 26 4 0,45 27 7 0,46 10 7 0,46 11 7 0,46 12 7 0,46 13 7 0,46 15 7 0,46 16 7 0,46 17 7 0,46 20 9 0,46 21 9 0,46 26 7 0,46 27 7 0,47 10 7 0,47 11 7 0,47 12 10 0,47 13 10 0,47 14 7 0,47 17 7 0,47 23 7 0,47 25 7 0,47 26 7 0,47 27 7 0,47 29 7 0,48 5 3 2,48 6 3 3,48 7 3 0,48 8 7 0,48 9 7 0,48 10 7 0,48 11 10 3,48 12 10 0,48 13 7 0,48 14 7 0,48 17 9 0,48 18 9 3,48 20 7 0,48 21 7 0,48 22 7 0,48 23 7 0,48 26 7 0,48 27 7 0,48 28 7 0,48 29 7 2,48 30 7 0,49 7 7 0,49 8 7 0,49 9 7 0,49 10 7 0,49 11 10 1,49 12 7 0,49 13 7 0,49 14 7 2,49 15 7 0,49 16 9 0,49 17 9 0,49 19 7 0,49 20 7 0,49 21 7 0,49 22 7 0,49 23 7 2,49 24 7 2,49 25 7 0,49 26 7 0,49 27 7 0,49 28 7 2,50 6 7 0,50 7 7 0,50 8 7 0,50 9 7 0,50 10 7 0,50 11 7 0,50 12 7 1,50 13 7 0,50 14 7 0,50 15 7 1,50 16 7 0,50 17 9 0,50 18 7 0,50 19 7 0,50 20 7 0,50 21 7 0,50 22 2 0,50 23 7 0,50 24 7 0,50 25 7 0,50 26 7 0,50 27 7 0,50 28 7 0,50 29 7 0,50 30 3 3,51 7 7 0,51 8 7 0,51 9 7 0,51 10 7 1,51 11 7 0,51 12 7 0,51 13 7 0,51 14 7 0,51 15 7 0,51 16 7 0,51 17 7 0,51 19 7 0,51 20 7 0,51 21 2 0,51 22 2 0,51 23 7 0,51 24 7 0,51 25 7 0,51 26 7 0,51 27 7 0,51 28 7 0,51 29 3 0,51 30 3 2,51 31 3 0,52 6 7 0,52 7 7 0,52 8 7 0,52 9 7 0,52 10 7 0,52 11 7 1,52 12 7 0,52 13 7 1,52 14 7 1,52 15 7 0,52 16 7 0,52 18 7 0,52 20 2 0,52 21 2 3,52 22 7 0,52 24 7 0,52 26 7 0,52 29 7 0,53 3 7 0,53 4 7 0,53 5 7 0,53 6 7 2,53 7 7 0,53 8 7 0,53 9 7 0,53 10 7 0,53 11 7 0,53 12 7 0,53 13 7 0,53 14 7 0,53 15 7 0,53 17 7 0,53 25 7 0,53 26 7 0,54 2 7 0,54 3 7 0,54 4 7 0,54 6 7 0,54 7 7 0,54 8 7 0,54 9 7 0,54 10 7 0,54 11 1 0,54 12 1 0,54 13 1 0,54 15 7 2,54 16 7 0,54 17 7 0,54 18 7 0,54 24 7 0,54 25 7 0,54 27 8 0,54 28 8 0,55 4 7 0,55 5 7 0,55 6 7 0,55 7 7 0,55 8 7 0,55 9 7 0,55 11 1 3,55 12 1 2,55 14 7 0,55 15 7 0,55 16 7 0,55 17 7 0,55 24 7 0,55 25 7 0,55 26 8 3,55 27 8 0,56 3 6 0,56 5 7 0,56 7 7 0,56 13 7 0,56 14 7 0,56 15 7 0,56 16 7 0,56 22 7 0,56 23 7 2,56 25 7 2,56 26 8 0,56 27 7 0,57 3 6 3,57 5 8 3,57 6 8 2,57 7 7 0,57 13 7 0,57 14 7 0,57 15 7 0,57 16 7 0,57 22 7 0,57 23 7 0,57 24 7 0,57 25 7 0,57 28 7 0,58 5 8 0,58 12 7 0,58 14 7 0,58 15 9 0,58 16 7 0,58 21 7 2,58 22 7 0,58 23 7 0,58 24 7 1,58 25 7 0,58 26 7 0,58 27 7 0,59 14 9 3,59 15 9 0,59 16 7 0,59 17 7 0,59 21 6 0,59 22 7 0,59 23 7 0,59 24 7 0,59 25 7 0,59 26 7 0,60 13 9 0,60 14 9 0,60 15 7 0,60 16 7 0,60 20 6 3,60 21 6 0,60 22 7 0,60 23 7 0,60 24 7 0,60 26 7 0,60 27 7 2,61 14 7 0,61 15 7 0,61 16 7 2,61 17 7 0,61 18 7 0,61 19 6 0,61 20 6 0,61 21 7 0,61 22 7 0,61 23 7 0,61 24 5 0,61 25 5 0,62 8 8 3,62 9 8 0,62 10 8 0,62 11 7 0,62 12 7 2,62 13 7 0,62 14 7 0,62 15 7 0,62 16 7 0,62 17 7 0,62 19 7 0,62 20 7 0,62 22 7 0,62 23 7 0,62 25 5 3,63 9 7 0,63 12 7 0,63 14 7 0,63 15 7 0,63 16 7 0,63 18 7 2,63 21 7 0,63 22 7 0,63 23 7 0,64 12 7 0,64 13 7 0,64 16 5 0,64 17 7 0,64 21 7 0,64 22 7 0,64 23 1 0,64 24 1 3,65 12 7 2,65 15 5 3,65 23 1 0,66 12 1 3,66 13 7 2,67 11 1 0,68 11 1 0,#units:#provinces:17@20@1@Kobrob@10,17@29@2@Nabnoi@10,17@37@3@Tektoiro@10,19@11@4@Aitroisk@10,20@37@5@Etoimai@10,21@21@6@Datpainsk@10,25@9@8@Bobrot@10,26@28@10@Mebkerg@10,28@15@9@Esame@10,29@18@12@Airbe-city@10,30@31@13@Maidoita@10,31@11@14@Abrensk@10,34@29@15@Rakre@10,36@10@16@Paiomova@10,37@17@17@Komavo@10,41@5@18@Sordo@10,41@25@19@Ebnepesk@10,43@5@20@Pebno-city@10,43@11@21@Airbepa@10,43@28@22@Debro@10,45@22@23@Tosso@10,47@12@24@Dakrer@10,48@5@25@Netamsk@10,48@17@26@Oikoaito@10,50@22@27@Orbabainsk@10,50@30@28@Moiboro@10,54@11@29@Otroi-city@10,54@27@30@Kotran@10,56@3@31@Kepomo@10,57@5@32@Rokook@10,58@15@33@Airabe@10,59@21@34@Ebnoikai@10,61@24@35@Oboto@10,62@8@36@Boskoi@10,64@16@37@Tokairg@10,64@23@38@Tarko@10,66@12@39@Marbemsk@10,#relations:#messages:#goal:def 0#`

**Comment by yiotro** [comment]
Thanks, but please don't submit maps here. Instead send them on my email (yiotro93@gmail.com) or post them in my subreddit: https://www.reddit.com/r/yiotro_games/
