### ISSUE TITLE
AI seems to stop working

### ISSUE THREAD

**Issue by MichaelS11** [yiotro/Antiyoy#85]
The AI sometimes seems to stop working. It does not move and does not respond to Diplomacy requests. Have had this happen on at least two different maps. Attacking the AI seems to clear the issue.

Version 1.26p

**Comment by MichaelS11** [comment]
Sorry, I meant to say I have not encountered it enough to see a pattern. I have only see it twice, so think it is quite rare.

Once the AI would not attack another AI yet I thought he did the turn before. I was not really watching that closely then so I thought I was just mistaken. Don't even recall the map.

The other level was Oleg8 where blue has captured the bottom island, I had the top two islands. Blue units would not move each turn, and it would not respond to or give any diplomacy requests. I probably need to play the map differently so have not made another attempt yet. Not a big fan of split maps so playing other maps at the moment.

**Comment by MichaelS11** [comment]
Unrelated, the map Chinese civil war has no human player for me.

**Comment by yiotro** [comment]
> Sorry, I meant to say I have not encountered it enough to see a pattern. I have only see it twice, so think it is quite rare.

Ok, no problem.

> Unrelated, the map Chinese civil war has no human player for me

Thanks, I'll fix that in next update.

**Comment by MichaelS11** [comment]
Thank you very much!
