### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by vincentwilliamrodriguez** [yiotro/Antiyoy#86]
Hi, here are some suggestions:
1. It seems that implementing boats and water travel in this game is difficult. But one good way that is similar to boats are connections between the part of the maps, so that units from a side of a connection can easily go to the other side of the connection. I think this wouldn't be that hard to implement
![Capture](https://user-images.githubusercontent.com/33214475/92904416-6dd08100-f455-11ea-9bc2-7478813b5dd4.PNG)

2. Holding down the base for all units to go towards that point is great, but it transfers all of the units, selecting only some units to move towards a point would be nice. This is not that hard too

Thanks

**Comment by yiotro** [comment]
Thanks for ideas.

> selecting only some units to move towards a point would be nice

How exactly should player select units?

**Comment by vincentwilliamrodriguez** [comment]
It can be through rectangular or free form selection. It can be also adjacent units like other games do

**Comment by vincentwilliamrodriguez** [comment]
Sorme other suggestions also:
3. I don't know if this is easy to implement, but line graph for live income replay would be nice.
4. Asking for name before saving a game/replay, this way it will be easier to recognize which is which.

**Comment by yiotro** [comment]
Thanks for suggestions.
About 4: do you know that you can rename replays and save slots?

**Comment by vincentwilliamrodriguez** [comment]
Yes, but renaming replays after saving them takes some time, rather than asking the name before saving, which is pretty quick. Also exporting editor games should ask for name too.

**Comment by vincentwilliamrodriguez** [comment]
Ok thanks for accepting the suggestions
