### ISSUE TITLE
Project Setup Error

### ISSUE THREAD

**Issue by NazarDoeH** [yiotro/Antiyoy#89]
HI I want to modify the game

but i have a problem running it
one of the problems is the code for android (which I commented on)
and the other is this:

error: YioGdxGame is not abstract and does not override abstract method scrolled(float,float) in InputProcessor
public class YioGdxGame extends ApplicationAdapter implements InputProcessor {
       ^

error: method does not override or implement a method from a supertype
    @Override
    ^

**Comment by yiotro** [comment]
Hi.

Please provide a screenshot of the problem, maybe I will be able to help.

Also, were you able to successfully compile sample libgdx project? (the one generated by gdx setup tool)

**Comment by NazarDoeH** [comment]
1)
![image](https://user-images.githubusercontent.com/57417144/101667066-8e5da680-3a57-11eb-9878-9546f4522c68.png)
![image](https://user-images.githubusercontent.com/57417144/101667100-99183b80-3a57-11eb-8358-8a7f53d7343f.png)
2)yes it compiled and launched without problems.
Hi ))

**Comment by Arkanosis** [comment]
It looks like your version of libgdx is more recent than the one used by @yiotro . The prototype of `scrolled` has changed in https://github.com/libgdx/libgdx/commit/432df1b58ab2d3fd5ce7d2892f663b8e1eac6f5e#diff-b30936e4220582acb1c05b729fb20cbf1d4c593dea354b6f97d539f942d9fc7e (that's between 1.9.11 and 1.9.12).
The backward-compatibility breaking nature of this change has been acknowledged in https://github.com/libgdx/libgdx/pull/6154 .

**Comment by NazarDoeH** [comment]
hmmm and how to change the version?

**Comment by subchannel13** [comment]
It should be an entry in core/core.iml but I see a hardcoded path to libgdx JAR there. Chances are you don't have an exact path on your machine, did compilation complain before?

And now I know dev's first name :)

**Comment by NazarDoeH** [comment]
did compilation complain before?
Blank ̶p̶̶̶r̶̶̶o̶̶̶j̶̶̶e̶̶̶c̶̶̶t̶̶̶ ̶̶̶s̶̶̶t̶̶̶a̶̶̶r̶̶̶t̶̶̶e̶̶̶d̶̶̶ ̶̶̶w̶̶̶i̶̶̶t̶̶̶h̶̶̶o̶̶̶u̶̶̶t̶̶̶ ̶̶̶p̶̶̶r̶̶̶o̶̶̶b̶̶̶l̶̶̶e̶̶̶m̶̶̶s̶
PS. There is a couple of warnings
dev's first name?

**Comment by subchannel13** [comment]
When you cloned or downloaded this game source code and tried to compile it, was there a complaint about missing libgdx JAR file? I don't understand Gradle scripts very well (or almost at all) but only place where I see libgdx referenced is in `core\core.iml` file, with the absolute path on dev's machine, containing dev's user name.

**Comment by NazarDoeH** [comment]
It works.
But I installed jdk 13 and gdx [1.9.11](https://github.com/tommyettinger/gdx-liftoff/releases).
Of course there are problems in the code but I just commented on them.
PS. to repair textures just run AtlasTextureCreator.jar which is in the assets\field_elements folder.
![image](https://user-images.githubusercontent.com/57417144/101989869-e5f45000-3cab-11eb-92ff-7a658d3d95c4.png)
