### ISSUE TITLE
Horizontal mode

### ISSUE THREAD

**Issue by ambient7** [yiotro/Antiyoy#90]
I love the game and i think it would be nice to be able to play in horizontal

**Comment by yiotro** [comment]
Hi.

Landscape mode would be nice but it's not that easy to implement as it may seem at first glance. Currently I can't promise that I'll do it.

**Comment by ambient7** [comment]
Oh ok, i also tought of a grid for the map editor, what do you think?

**Comment by yiotro** [comment]
You can enable 'grid' skin in game options, it will solve the problem :)

**Comment by yiotro** [comment]
You can enable 'grid' skin in game options, it will solve the problem :)

пт, 18 дек. 2020 г. в 19:57, ambient7 <notifications@github.com>:
