### ISSUE TITLE
Suggestions II

### ISSUE THREAD

**Issue by vincentwilliamrodriguez** [yiotro/Antiyoy#91]
Hi, here are some suggestions. Hope they get implemented soon.

For the User levels section:
1. Concerning the filters, it might be better to use dropdown menu instead of checkbox in order to be more organized and to provide more options, for example:
Progress
-Any
-New
-Completed
Type
-Any
-Hisorical
-Non-historical
Players
-Any
-Single player
-Multiplayer

Etc.

2. About the filters too, searching by author would be good.
3. Ability to permanently hide an user level.

For the Replay section:
1. Forward and backwards button by 1 turn.
2. Replay of fog of war for one player.
3. Replay of diplomatic relations.

For Diplomacy:
1. It would be better if a nation's name will remain the same throughout the game. Sometimes a nation splits resulting in another name.

This game is already good, but can be made better. Thanks.

**Comment by yiotro** [comment]
Hi.

Thanks for ideas, I'll think about them. Though I have to say that this section is for issues, not for suggestions. Please use email (yiotro93@gmail.com) for that.
